let age=16;
let price = 10.99;
let gpa = 2.8;
document.getElementById("gpa").textContent=gpa;
document.getElementById("price").textContent=price;
document.getElementById("age").textContent=age;
console.log(typeof gpa);
console.log(`You are ${age} years old`);
console.log(`You are ${gpa}`);
console.log(`The price are ${price}`);